# Generated by Django 5.1.3 on 2024-11-06 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='auth_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='service',
            name='url',
            field=models.URLField(default='https://abc.com'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='status',
            field=models.CharField(max_length=10),
        ),
    ]
