# Generated by Django 5.1.3 on 2024-11-06 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health_check', '0002_service_auth_token_service_url_alter_service_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
